[package]
name = "serde_querystring"
version = "0.0.1"
authors = ["Pouya M. B. <pooyamb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = { version = "1" }

[dev-dependencies]
criterion = "0.3"
serde_urlencoded = "0.7"
serde_qs = "0.7"
serde = { version = "1", features = ["derive"] }

[[bench]]
name = "simple"
harness = false

[[bench]]
name = "struct"
harness = false

[[bench]]
name = "decoded"
harness = false

[[bench]]
name = "child"
harness = false

[[bench]]
name = "multilevel"
harness = false

[profile.bench]
lto = true
