[package]
name = "serde-querystring-actix"
version = "0.0.7"
authors = ["Pouya M. B. <pooyamb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
actix-web = "3"
serde = "1"
derive_more = "0.99"
log = "0.4"
serde-querystring = "0.0.7"

[dev-dependencies]
actix-rt = "1"
